/**
 * action 的类型变量
 */

module.exports = {
	NETWORK_INDICATOR: 'NETWORK_INDICATOR',
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
	RACING_LIST_REQUEST:'RACING_LIST_REQUEST',
	RACING_LIST_SUCCESS:'RACING_LIST_SUCCESS',
	RACING_LIST_FAILURE:'RACING_LIST_FAILURE'
}